name: Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install -r requirements_dev.txt

      - name: Run autopep8
        run: autopep8 --in-place --recursive .

      - name: Run Pylint
        continue-on-error: true
        run: pylint **/*.py > post_traces/pylint_trace.txt

      - name: Display Pylint Results
        run: cat post_traces/pylint_trace.txt

      - name: Run Pyright
        continue-on-error: true
        run: pyright **/*.py > post_traces/pyright_trace.txt

      - name: Display Pyright Results
        run: cat post_traces/pyright_trace.txt

      - name: Commit changes
        run: |
          git config --global user.name 'Akshay Dongare'
          git config --global user.email 'akshayd02@gmail.com'
          git add .
          git diff --staged --exit-code || git commit -m "Apply autopep8 and static analysis tools (pylint, pyright) fixes" || echo "No changes to commit"
          git push