name: Static Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  analysis:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.13", "3.12"]
    
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install Dependencies
        run: pip install -r requirements_dev.txt

      - name: Run autopep8
        run: |
          autopep8 --in-place --recursive .
          git diff > post_traces/autopep8_trace__from_workflow.txt

      - name: Display autopep8 Changes
        run: cat post_traces/autopep8_trace__from_workflow.txt

      - name: Run Pylint
        continue-on-error: true
        run: pylint **/*.py --output-format=colorized --reports=y > post_traces/pylint_trace_from_workflow.txt 2>&1

      - name: Display Pylint Results
        run: cat post_traces/pylint_trace_from_workflow.txt

      - name: Run Pyright
        continue-on-error: true
        run: pyright **/*.py > post_traces/pyright_trace_from_workflow.txt

      - name: Display Pyright Results
        run: cat post_traces/pyright_trace_from_workflow.txt

      - name: Commit changes
        continue-on-error: true
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            DATE=$(date '+%Y-%m-%d %H:%M:%S')
            git commit -m "Code quality improvements by static analysis workflow applied on $DATE"
            git push
          fi
